#!/usr/bin/env bash

# Get all network interfaces
interfaces=$(ifconfig | awk -F':' '/^[a-z]/ && !/^lo/ {print $1}')

#loop through each interface and get the IPv4 address
for interface in $interfaces; do
	ip=$(ifconfig $interface | awk '/inet / {print $2}')
	echo $ip
done
